
---
name: Build IPC and Upload to S3

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-and-upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libtool autoconf unzip wget \
            libssl-dev libssh-dev ninja-build pkg-config

      - name: Install CMake 3.29.2
        run: |
          version=3.29
          build=2
          mkdir ~/temp && cd ~/temp
          wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
          tar -xzf cmake-$version.$build.tar.gz
          cd cmake-$version.$build
          ./bootstrap
          make -j$(nproc)
          sudo make install

      - name: Build libipc.a
        run: |
          mkdir build && cd build
          cmake .. -DIPC_ENABLE_TESTING=OFF
          make -j$(nproc)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::203647640528:role/GitHubActionsArtifactUploaderRole
          aws-region: eu-west-1

      - name: Upload to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: edge-to-cloud-bucket
          region: eu-west-1
          source: build/
          destination: build-artifacts/github-sdv-poc-msp-ipc/

