---
name: Build aws-iot-bridge and Upload to S3

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Install Git for checkout
        run: |
          apt-get update
          apt-get install -y git ca-certificates

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Install build deps
        run: |
          set -e
          apt-get update
          apt-get install -y  \
            build-essential libtool autoconf unzip wget curl \
            ninja-build pkg-config file binutils \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            qemu-user-static binfmt-support python3 python3-pip ca-certificates
          
          dpkg --add-architecture arm64
          apt-get update
          apt-get install -y --no-install-recommends \
            libc6:arm64 libstdc++6:arm64 zlib1g:arm64 \
            libssl-dev:arm64 libssh-dev:arm64 libcurl4-openssl-dev:arm64
      
      - name: Install CMake via pip (3.17)
        run: |
          set -e
          python3 -m pip install --user "cmake==3.17"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          which cmake
          cmake --version

      - name: Build aws-iot-bridge
        env:
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
        run: |
          ./build.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::410849528398:role/GitHubActionsArtifactUploaderRole
          aws-region: us-east-2

      - name: Upload aws-iot-bridge to S3
        run: |
          if [ -f ./build/aws_iot_bridge_app ]; then
            aws s3 cp ./build/aws_iot_bridge_app \
              s3://nvidia-edge-to-cloud-bucket/build_artifacts/nvidia-aws-iot-bridge/aws_iot_bridge_app \
              --region us-east-2
            aws s3 cp ./resources/configs/main_config.json \
              s3://nvidia-edge-to-cloud-bucket/build_artifacts/nvidia-aws-iot-bridge/ \
              --region us-east-2
          else
            echo "aws-iot-bridge not found, skipping upload."
          fi