name: Run IPC Unit Tests

on:
  pull_request:
    types: [closed]

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libtool autoconf unzip wget \
            libssl-dev libssh-dev ninja-build pkg-config

      - name: Install CMake 3.29.2
        run: |
          version=3.29
          build=2
          mkdir ~/temp && cd ~/temp
          wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
          tar -xzf cmake-$version.$build.tar.gz
          cd cmake-$version.$build
          ./bootstrap
          make -j$(nproc)
          sudo make install

      - name: Build with tests
        run: |
          mkdir build && cd build
          cmake .. -DIPC_ENABLE_TESTING=ON
          make -j$(nproc)

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure

